// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.mit.cci.simulation.model;

import edu.mit.cci.simulation.model.TupleDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TupleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TupleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TupleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TupleIntegrationTest: @Transactional;
    
    @Autowired
    private TupleDataOnDemand TupleIntegrationTest.dod;
    
    @Test
    public void TupleIntegrationTest.testCountTuples() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to initialize correctly", dod.getRandomTuple());
        long count = edu.mit.cci.simulation.model.Tuple.countTuples();
        org.junit.Assert.assertTrue("Counter for 'Tuple' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TupleIntegrationTest.testFindTuple() {
        edu.mit.cci.simulation.model.Tuple obj = dod.getRandomTuple();
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Tuple.findTuple(id);
        org.junit.Assert.assertNotNull("Find method for 'Tuple' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Tuple' returned the incorrect identifier", id, obj.getId());
    }
    
    //@Test
    public void TupleIntegrationTest.testFindAllTuples() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to initialize correctly", dod.getRandomTuple());
        long count = edu.mit.cci.simulation.model.Tuple.countTuples();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Tuple', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.mit.cci.simulation.model.Tuple> result = edu.mit.cci.simulation.model.Tuple.findAllTuples();
        org.junit.Assert.assertNotNull("Find all method for 'Tuple' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Tuple' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TupleIntegrationTest.testFindTupleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to initialize correctly", dod.getRandomTuple());
        long count = edu.mit.cci.simulation.model.Tuple.countTuples();
        if (count > 20) count = 20;
        java.util.List<edu.mit.cci.simulation.model.Tuple> result = edu.mit.cci.simulation.model.Tuple.findTupleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Tuple' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Tuple' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TupleIntegrationTest.testFlush() {
        edu.mit.cci.simulation.model.Tuple obj = dod.getRandomTuple();
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Tuple.findTuple(id);
        org.junit.Assert.assertNotNull("Find method for 'Tuple' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTuple(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Tuple' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TupleIntegrationTest.testMerge() {
        edu.mit.cci.simulation.model.Tuple obj = dod.getRandomTuple();
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Tuple.findTuple(id);
        boolean modified =  dod.modifyTuple(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.mit.cci.simulation.model.Tuple merged = (edu.mit.cci.simulation.model.Tuple) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Tuple' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TupleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to initialize correctly", dod.getRandomTuple());
        edu.mit.cci.simulation.model.Tuple obj = dod.getNewTransientTuple(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Tuple' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Tuple' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Tuple' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TupleIntegrationTest.testRemove() {
         DefaultVariable v = new DefaultVariable();
        v.persist();
        edu.mit.cci.simulation.model.Tuple obj = new Tuple(v);

        obj.persist();
        org.junit.Assert.assertNotNull("'Tuple' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("'Tuple' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Tuple.findTuple(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Tuple' with identifier '" + id + "'", edu.mit.cci.simulation.model.Tuple.findTuple(id));
    }
    
}
