// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.mit.cci.amt.framwork;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Workflow_Roo_Configurable {
    
    declare @type: Workflow: @Configurable;
    
}
