// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.mit.cci.simulation.model;

import edu.mit.cci.simulation.model.DefaultSimulationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DefaultSimulationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DefaultSimulationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DefaultSimulationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DefaultSimulationIntegrationTest: @Transactional;
    
    @Autowired
    private DefaultSimulationDataOnDemand DefaultSimulationIntegrationTest.dod;
    
    @Test
    public void DefaultSimulationIntegrationTest.testCountDefaultSimulations() {
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", dod.getRandomDefaultSimulation());
        long count = edu.mit.cci.simulation.model.DefaultSimulation.countDefaultSimulations();
        org.junit.Assert.assertTrue("Counter for 'DefaultSimulation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DefaultSimulationIntegrationTest.testFindDefaultSimulation() {
        edu.mit.cci.simulation.model.DefaultSimulation obj = dod.getRandomDefaultSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.DefaultSimulation.findDefaultSimulation(id);
        org.junit.Assert.assertNotNull("Find method for 'DefaultSimulation' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'DefaultSimulation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DefaultSimulationIntegrationTest.testFindAllDefaultSimulations() {
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", dod.getRandomDefaultSimulation());
        long count = edu.mit.cci.simulation.model.DefaultSimulation.countDefaultSimulations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'DefaultSimulation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.mit.cci.simulation.model.DefaultSimulation> result = edu.mit.cci.simulation.model.DefaultSimulation.findAllDefaultSimulations();
        org.junit.Assert.assertNotNull("Find all method for 'DefaultSimulation' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'DefaultSimulation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DefaultSimulationIntegrationTest.testFindDefaultSimulationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", dod.getRandomDefaultSimulation());
        long count = edu.mit.cci.simulation.model.DefaultSimulation.countDefaultSimulations();
        if (count > 20) count = 20;
        java.util.List<edu.mit.cci.simulation.model.DefaultSimulation> result = edu.mit.cci.simulation.model.DefaultSimulation.findDefaultSimulationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'DefaultSimulation' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'DefaultSimulation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DefaultSimulationIntegrationTest.testFlush() {
        edu.mit.cci.simulation.model.DefaultSimulation obj = dod.getRandomDefaultSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.DefaultSimulation.findDefaultSimulation(id);
        org.junit.Assert.assertNotNull("Find method for 'DefaultSimulation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDefaultSimulation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'DefaultSimulation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DefaultSimulationIntegrationTest.testMerge() {
        edu.mit.cci.simulation.model.DefaultSimulation obj = dod.getRandomDefaultSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.DefaultSimulation.findDefaultSimulation(id);
        boolean modified =  dod.modifyDefaultSimulation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.mit.cci.simulation.model.DefaultSimulation merged = (edu.mit.cci.simulation.model.DefaultSimulation) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'DefaultSimulation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DefaultSimulationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", dod.getRandomDefaultSimulation());
        edu.mit.cci.simulation.model.DefaultSimulation obj = dod.getNewTransientDefaultSimulation(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'DefaultSimulation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'DefaultSimulation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DefaultSimulationIntegrationTest.testRemove() {
        edu.mit.cci.simulation.model.DefaultSimulation obj = dod.getRandomDefaultSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DefaultSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.DefaultSimulation.findDefaultSimulation(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'DefaultSimulation' with identifier '" + id + "'", edu.mit.cci.simulation.model.DefaultSimulation.findDefaultSimulation(id));
    }
    
}
