// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.mit.cci.simulation.model;

import edu.mit.cci.simulation.model.MappedSimulationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MappedSimulationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MappedSimulationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MappedSimulationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MappedSimulationIntegrationTest: @Transactional;
    
    @Autowired
    private MappedSimulationDataOnDemand MappedSimulationIntegrationTest.dod;
    
    @Test
    public void MappedSimulationIntegrationTest.testCountMappedSimulations() {
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", dod.getRandomMappedSimulation());
        long count = edu.mit.cci.simulation.model.MappedSimulation.countMappedSimulations();
        org.junit.Assert.assertTrue("Counter for 'MappedSimulation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MappedSimulationIntegrationTest.testFindMappedSimulation() {
        edu.mit.cci.simulation.model.MappedSimulation obj = dod.getRandomMappedSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.MappedSimulation.findMappedSimulation(id);
        org.junit.Assert.assertNotNull("Find method for 'MappedSimulation' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MappedSimulation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MappedSimulationIntegrationTest.testFindAllMappedSimulations() {
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", dod.getRandomMappedSimulation());
        long count = edu.mit.cci.simulation.model.MappedSimulation.countMappedSimulations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MappedSimulation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.mit.cci.simulation.model.MappedSimulation> result = edu.mit.cci.simulation.model.MappedSimulation.findAllMappedSimulations();
        org.junit.Assert.assertNotNull("Find all method for 'MappedSimulation' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MappedSimulation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MappedSimulationIntegrationTest.testFindMappedSimulationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", dod.getRandomMappedSimulation());
        long count = edu.mit.cci.simulation.model.MappedSimulation.countMappedSimulations();
        if (count > 20) count = 20;
        java.util.List<edu.mit.cci.simulation.model.MappedSimulation> result = edu.mit.cci.simulation.model.MappedSimulation.findMappedSimulationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MappedSimulation' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MappedSimulation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MappedSimulationIntegrationTest.testFlush() {
        edu.mit.cci.simulation.model.MappedSimulation obj = dod.getRandomMappedSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.MappedSimulation.findMappedSimulation(id);
        org.junit.Assert.assertNotNull("Find method for 'MappedSimulation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMappedSimulation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MappedSimulation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MappedSimulationIntegrationTest.testMerge() {
        edu.mit.cci.simulation.model.MappedSimulation obj = dod.getRandomMappedSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.MappedSimulation.findMappedSimulation(id);
        boolean modified =  dod.modifyMappedSimulation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.mit.cci.simulation.model.MappedSimulation merged = (edu.mit.cci.simulation.model.MappedSimulation) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MappedSimulation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MappedSimulationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", dod.getRandomMappedSimulation());
        edu.mit.cci.simulation.model.MappedSimulation obj = dod.getNewTransientMappedSimulation(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MappedSimulation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MappedSimulation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MappedSimulationIntegrationTest.testRemove() {
        edu.mit.cci.simulation.model.MappedSimulation obj = dod.getRandomMappedSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MappedSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.MappedSimulation.findMappedSimulation(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MappedSimulation' with identifier '" + id + "'", edu.mit.cci.simulation.model.MappedSimulation.findMappedSimulation(id));
    }
    
}
