// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.mit.cci.simulation.model;

import edu.mit.cci.simulation.model.Variable;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect VariableDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VariableDataOnDemand: @Component;
    
    private Random VariableDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Variable> VariableDataOnDemand.data;
    
    public Variable VariableDataOnDemand.getNewTransientVariable(int index) {
        edu.mit.cci.simulation.model.Variable obj = new edu.mit.cci.simulation.model.Variable();
        obj.setName(null);
        obj.setDescription(null);
        obj.setArity(new Integer(index));
        obj.setDataType(null);
        obj.setPrecision_(null);
        obj.setMax_(null);
        obj.setMin_(null);
        obj.set_optionsRaw("_optionsRaw_" + index);
        obj.setIndexingVariable(null);
        return obj;
    }
    
    public Variable VariableDataOnDemand.getSpecificVariable(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Variable obj = data.get(index);
        return Variable.findVariable(obj.getId());
    }
    
    public Variable VariableDataOnDemand.getRandomVariable() {
        init();
        Variable obj = data.get(rnd.nextInt(data.size()));
        return Variable.findVariable(obj.getId());
    }
    
    public boolean VariableDataOnDemand.modifyVariable(Variable obj) {
        return false;
    }
    
    public void VariableDataOnDemand.init() {
        data = edu.mit.cci.simulation.model.Variable.findVariableEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Variable' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.mit.cci.simulation.model.Variable>();
        for (int i = 0; i < 10; i++) {
            edu.mit.cci.simulation.model.Variable obj = getNewTransientVariable(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
