// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.mit.cci.simulation.model;

import edu.mit.cci.simulation.model.VariableDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VariableIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VariableIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VariableIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: VariableIntegrationTest: @Transactional;
    
    @Autowired
    private VariableDataOnDemand VariableIntegrationTest.dod;
    
    @Test
    public void VariableIntegrationTest.testCountVariables() {
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", dod.getRandomVariable());
        long count = edu.mit.cci.simulation.model.Variable.countVariables();
        org.junit.Assert.assertTrue("Counter for 'Variable' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VariableIntegrationTest.testFindVariable() {
        edu.mit.cci.simulation.model.Variable obj = dod.getRandomVariable();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Variable.findVariable(id);
        org.junit.Assert.assertNotNull("Find method for 'Variable' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Variable' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VariableIntegrationTest.testFindAllVariables() {
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", dod.getRandomVariable());
        long count = edu.mit.cci.simulation.model.Variable.countVariables();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Variable', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.mit.cci.simulation.model.Variable> result = edu.mit.cci.simulation.model.Variable.findAllVariables();
        org.junit.Assert.assertNotNull("Find all method for 'Variable' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Variable' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VariableIntegrationTest.testFindVariableEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", dod.getRandomVariable());
        long count = edu.mit.cci.simulation.model.Variable.countVariables();
        if (count > 20) count = 20;
        java.util.List<edu.mit.cci.simulation.model.Variable> result = edu.mit.cci.simulation.model.Variable.findVariableEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Variable' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Variable' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VariableIntegrationTest.testFlush() {
        edu.mit.cci.simulation.model.Variable obj = dod.getRandomVariable();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Variable.findVariable(id);
        org.junit.Assert.assertNotNull("Find method for 'Variable' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVariable(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Variable' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VariableIntegrationTest.testMerge() {
        edu.mit.cci.simulation.model.Variable obj = dod.getRandomVariable();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Variable.findVariable(id);
        boolean modified =  dod.modifyVariable(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.mit.cci.simulation.model.Variable merged = (edu.mit.cci.simulation.model.Variable) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Variable' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VariableIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", dod.getRandomVariable());
        edu.mit.cci.simulation.model.Variable obj = dod.getNewTransientVariable(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Variable' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Variable' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VariableIntegrationTest.testRemove() {
        edu.mit.cci.simulation.model.Variable obj = dod.getRandomVariable();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Variable' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.model.Variable.findVariable(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Variable' with identifier '" + id + "'", edu.mit.cci.simulation.model.Variable.findVariable(id));
    }
    
}
