// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.mit.cci.simulation.excel.server;

import edu.mit.cci.simulation.excel.server.ExcelSimulationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExcelSimulationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExcelSimulationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExcelSimulationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ExcelSimulationIntegrationTest: @Transactional;
    
    @Autowired
    private ExcelSimulationDataOnDemand ExcelSimulationIntegrationTest.dod;
    
    @Test
    public void ExcelSimulationIntegrationTest.testCountExcelSimulations() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", dod.getRandomExcelSimulation());
        long count = edu.mit.cci.simulation.excel.server.ExcelSimulation.countExcelSimulations();
        org.junit.Assert.assertTrue("Counter for 'ExcelSimulation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExcelSimulationIntegrationTest.testFindExcelSimulation() {
        edu.mit.cci.simulation.excel.server.ExcelSimulation obj = dod.getRandomExcelSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.excel.server.ExcelSimulation.findExcelSimulation(id);
        org.junit.Assert.assertNotNull("Find method for 'ExcelSimulation' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ExcelSimulation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExcelSimulationIntegrationTest.testFindAllExcelSimulations() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", dod.getRandomExcelSimulation());
        long count = edu.mit.cci.simulation.excel.server.ExcelSimulation.countExcelSimulations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ExcelSimulation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.mit.cci.simulation.excel.server.ExcelSimulation> result = edu.mit.cci.simulation.excel.server.ExcelSimulation.findAllExcelSimulations();
        org.junit.Assert.assertNotNull("Find all method for 'ExcelSimulation' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ExcelSimulation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExcelSimulationIntegrationTest.testFindExcelSimulationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", dod.getRandomExcelSimulation());
        long count = edu.mit.cci.simulation.excel.server.ExcelSimulation.countExcelSimulations();
        if (count > 20) count = 20;
        java.util.List<edu.mit.cci.simulation.excel.server.ExcelSimulation> result = edu.mit.cci.simulation.excel.server.ExcelSimulation.findExcelSimulationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ExcelSimulation' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ExcelSimulation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExcelSimulationIntegrationTest.testFlush() {
        edu.mit.cci.simulation.excel.server.ExcelSimulation obj = dod.getRandomExcelSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.excel.server.ExcelSimulation.findExcelSimulation(id);
        org.junit.Assert.assertNotNull("Find method for 'ExcelSimulation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExcelSimulation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ExcelSimulation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExcelSimulationIntegrationTest.testMerge() {
        edu.mit.cci.simulation.excel.server.ExcelSimulation obj = dod.getRandomExcelSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.excel.server.ExcelSimulation.findExcelSimulation(id);
        boolean modified =  dod.modifyExcelSimulation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.mit.cci.simulation.excel.server.ExcelSimulation merged = (edu.mit.cci.simulation.excel.server.ExcelSimulation) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ExcelSimulation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExcelSimulationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", dod.getRandomExcelSimulation());
        edu.mit.cci.simulation.excel.server.ExcelSimulation obj = dod.getNewTransientExcelSimulation(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ExcelSimulation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ExcelSimulation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExcelSimulationIntegrationTest.testRemove() {
        edu.mit.cci.simulation.excel.server.ExcelSimulation obj = dod.getRandomExcelSimulation();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExcelSimulation' failed to provide an identifier", id);
        obj = edu.mit.cci.simulation.excel.server.ExcelSimulation.findExcelSimulation(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ExcelSimulation' with identifier '" + id + "'", edu.mit.cci.simulation.excel.server.ExcelSimulation.findExcelSimulation(id));
    }
    
}
